version: "3.9"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=parse
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local

